framework: mocha
serve_files:
  - "./test/promisr.js"
test_page: ./test/index.html
before_tests: |
  browserify ./test/index.js \
  --outfile ./test/promisr.js \
  --transform browserify-shim \
  --standalone Promisr
after_tests: rm ./test/promisr.js
